name: 'bulckan'

networks:
  bulckan:

volumes:
  repo1:
  repo2:
  repo3:

services:
  bulckan1:
    image: ghcr.io/dockopslab/bulckan:latest
    env_file:
      - .git.env
    environment:
      - GITHUB_URL=github.com/dockopslab/bulckan.git
      - GITHUB_BRANCH=example/bulckan-target
      - GITHUB_PATH=watchtower/
      - CHECK_INTERVAL=3600
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - repo1:/repo
      # - .repo1:/repo
    networks:
      - bulckan
  
  bulckan2:
    image: ghcr.io/dockopslab/bulckan:latest
    env_file:
      - .git.env
    environment:
      - GITHUB_URL=github.com/dockopslab/bulckan.git
      - GITHUB_BRANCH=example/bulckan-target
      - GITHUB_PATH=sample/
      - CHECK_INTERVAL=120
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - repo2:/repo
      # - .repo2:/repo
    networks:
      - bulckan

  bulckan3:
    image: ghcr.io/dockopslab/bulckan:latest
    env_file:
      - .git.env
    environment:
      - GITHUB_URL=github.com/dockopslab/bulckan.git
      - GITHUB_BRANCH=example/bulckan-target
      - GITHUB_PATH=sample1/
      - CHECK_INTERVAL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - repo3:/repo
      # - .repo3:/repo
    networks:
      - bulckan

  # ...